### ISSUE TITLE
Add additional information to the lake data

### ISSUE THREAD

**Issue by matlads** [nakiwuge/uganda-lakes#6]
Wikipedia and Lakepedia provide a lot more information about lakes like (but not limited to)

1. Max Length
2. Max Width
3. Surface Area
4. Surface Elevation
5. District
6. Primary inflows
7. Primary outflows
8. Max depth
9. Average depth
10. isDammed?

It would be awesome, if this module, included this information as well.

**Comment by nakiwuge** [comment]
> Wikipedia and Lakepedia provide a lot more information about lakes like (but not limited to)
> 
> 1. Max Length
> 2. Max Width
> 3. Surface Area
> 4. Surface Elevation
> 5. District
> 6. Primary inflows
> 7. Primary outflows
> 8. Max depth
> 9. Average depth
> 10. isDammed?
> 
> It would be awesome, if this module, included this information as well.

@matlads, Thanks for raising this issue. I am going to work on it.
